In [1]:
import pyAERONET

ModuleNotFoundError: No module named 'functions'

In [6]:
df = pd.read_csv('Sao_Paulo_AOD20.csv')
compute_AOD550nm(df,return_columns=['time','AOD_550nm','440-870_Angstrom_Exponent'])

                     time  AOD_550nm  440-870_Angstrom_Exponent
0     2010-01-04 10:48:58   0.202177                   1.376145
1     2010-01-04 11:27:34   0.183635                   1.034662
2     2010-01-04 14:57:39   0.201782                   1.464260
3     2010-01-04 15:27:38   0.163659                   1.514056
4     2010-01-05 11:43:01   0.291278                   1.058401
...                   ...        ...                        ...
4192  2012-02-08 12:52:10   0.227250                   1.635734
4193  2012-02-09 15:07:14   0.252377                   1.360979
4194  2012-02-10 11:35:32   0.566636                   1.271431
4195  2012-02-10 15:37:16   0.244904                   1.593075
4196  2012-02-10 17:07:17   0.235702                   1.685218

[4197 rows x 3 columns]

In [ ]:
view_data(station='Sao_Paulo',
         start_date='2010-01-01',
         end_date='2014-01-01',
         vars='AOD20',
         data_frequency='all')

,AERONET_Site,Date(dd:mm:yyyy),Time(hh:mm:ss),Day_of_Year,Day_of_Year(Fraction),AOD_1640nm,AOD_1020nm,AOD_870nm,AOD_865nm,AOD_779nm,...,Exact_Wavelengths_of_AOD(um)_340nm,Exact_Wavelengths_of_PW(um)_935nm,Exact_Wavelengths_of_AOD(um)_681nm,Exact_Wavelengths_of_AOD(um)_709nm,Exact_Wavelengths_of_AOD(um)_Empty,Exact_Wavelengths_of_AOD(um)_Empty_duplicated_0,Exact_Wavelengths_of_AOD(um)_Empty_duplicated_1,Exact_Wavelengths_of_AOD(um)_Empty_duplicated_2,Exact_Wavelengths_of_AOD(um)_Empty_duplicated_3,Principal_Investigator
0,Sao_Paulo,04:01:2010,10:48:58,4,4.450671,-999.0,-999.000000,0.108997,-999.0,-999.0,...,0.3397,0.9362,-999.0,-999.0,-999.0,-999.0,-999.0,-999.0,-999.0,PI=Paulo_Artaxo; PI Email=artaxo@if.usp.br
1,Sao_Paulo,04:01:2010,11:27:34,4,4.477477,-999.0,-999.000000,0.118856,-999.0,-999.0,...,0.3397,0.9362,-999.0,-999.0,-999.0,-999.0,-999.0,-999.0,-999.0,PI=Paulo_Artaxo; PI Email=artaxo@if.usp.br
2,Sao_Paulo,04:01:2010,14:57:39,4,4.623368,-999.0,-999.000000,0.100304,-999.0,-999.0,...,0.3397,0.9362,-999.0,-999.0,-999.0,-999.0,-999.0,-999.0,-999.0,PI=Paulo_Artaxo; PI Email=artaxo@if.usp.br
3,Sao_Paulo,04:01:2010,15:27:38,4,4.644190,-999.0,-999.000000,0.078488,-999.0,-999.0,...,0.3397,0.9362,-999.0,-999.0,-999.0,-999.0,-999.0,-999.0,-999.0,PI=Paulo_Artaxo; PI Email=artaxo@if.usp.br
4,Sao_Paulo,05:01:2010,11:43:01,5,5.488206,-999.0,-999.000000,0.174075,-999.0,-999.0,...,0.3397,0.9362,-999.0,-999.0,-999.0,-999.0,-999.0,-999.0,-999.0,PI=Paulo_Artaxo; PI Email=artaxo@if.usp.br
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4192,Sao_Paulo,08:02:2012,12:52:10,39,39.536227,-999.0,0.088835,0.109949,-999.0,-999.0,...,0.3391,0.9358,-999.0,-999.0,-999.0,-999.0,-999.0,-999.0,-999.0,PI=Paulo_Artaxo; PI Email=artaxo@if.usp.br
4193,Sao_Paulo,09:02:2012,15:07:14,40,40.630023,-999.0,0.118727,0.139900,-999.0,-999.0,...,0.3391,0.9358,-999.0,-999.0,-999.0,-999.0,-999.0,-999.0,-999.0,PI=Paulo_Artaxo; PI Email=artaxo@if.usp.br
4194,Sao_Paulo,10:02:2012,11:35:32,41,41.483009,-999.0,0.235164,0.300208,-999.0,-999.0,...,0.3391,0.9358,-999.0,-999.0,-999.0,-999.0,-999.0,-999.0,-999.0,PI=Paulo_Artaxo; PI Email=artaxo@if.usp.br
4195,Sao_Paulo,10:02:2012,15:37:16,41,41.650880,-999.0,0.093795,0.118623,-999.0,-999.0,...,0.3391,0.9358,-999.0,-999.0,-999.0,-999.0,-999.0,-999.0,-999.0,PI=Paulo_Artaxo; PI Email=artaxo@if.usp.br
4196,Sao_Paulo,10:02:2012,17:07:17,41,41.713391,-999.0,0.087246,0.109313,-999.0,-999.0,...,0.3391,0.9358,-999.0,-999.0,-999.0,-999.0,-999.0,-999.0,-999.0,PI=Paulo_Artaxo; PI Email=artaxo@if.usp.br

In [12]:
df_all = pd.read_csv('Sao_Paulo_ALL.csv')
compute_broadband(df_all)[['time','ssa_broadband','asy_broadband','surface_albedo_broadband']].head(10)

                  time  ssa_broadband  asy_broadband  surface_albedo_broadband
0  2010-08-27 18:11:00       0.798428       0.608350                  0.114943
1  2010-08-27 18:33:28       0.801800       0.617090                  0.118449
2  2010-08-28 10:33:51       0.912606       0.712697                  0.135676
3  2010-08-28 10:56:51       0.905311       0.709768                  0.127809
4  2010-08-28 11:47:16       0.898936       0.701038                  0.116812
5  2010-08-28 12:10:46       0.873858       0.681571                  0.113560
6  2010-08-28 18:10:49       0.845685       0.624713                  0.114827
7  2010-08-28 18:34:16       0.835404       0.614897                  0.118487
8  2010-08-28 19:24:41       0.854191       0.620815                  0.130956
9  2010-08-28 19:48:57       0.848070       0.602718                  0.140593