Importando as bibliotecas

In [ ]:
import pyAERONET
import polars as pl

Realizando o download de todas as variáveis de 'retrieval' da AERONET.

In [5]:
pyAERONET.GetDataAERONET(station='Sao_Paulo',
                     start_date='2002-02-1',
                     end_date='2020-10-1',
                     vars='ALL',
                     inversion_type='ALM20',
                     temporal_type='all')

Finish Download: 100%|██████████| 3/3 [00:10<00:00,  3.46s/it]

Veja que as propriedades são em linhas espectrais *440 nm*, *675 nm*, *870 nm* e *1020 nm*.

In [38]:
df = pl.read_csv('Sao_Paulo_ALL.csv')
df.columns[:10]

['time',
 'AERONET_Site',
 'Day_of_Year',
 'Day_of_Year(Fraction)',
 'AOD_Coincident_Input[440nm]',
 'AOD_Coincident_Input[675nm]',
 'AOD_Coincident_Input[870nm]',
 'AOD_Coincident_Input[1020nm]',
 'Angstrom_Exponent_440-870nm_from_Coincident_Input_AOD',
 'AOD_Extinction-Total[440nm]']

Calculando as variáveis fator de assimetria, albedo simples e albedo de superfície 
em bandalarga.

In [39]:
pyAERONET.calcular_broadband_aeronet(df)['time','ssa_broadband','asy_broadband','surface_albedo_broadband'].head(5)

shape: (5, 4)
┌─────────────────────┬───────────────┬───────────────┬──────────────────────────┐
│ time                ┆ ssa_broadband ┆ asy_broadband ┆ surface_albedo_broadband │
│ ---                 ┆ ---           ┆ ---           ┆ ---                      │
│ str                 ┆ f64           ┆ f64           ┆ f64                      │
╞═════════════════════╪═══════════════╪═══════════════╪══════════════════════════╡
│ 2002-04-11 10:28:17 ┆ -999.0        ┆ 0.741715      ┆ 0.150063                 │
│ 2002-04-11 12:09:54 ┆ -999.0        ┆ 0.686575      ┆ 0.12324                  │
│ 2002-04-16 11:44:23 ┆ -999.0        ┆ 0.686456      ┆ 0.125923                 │
│ 2002-04-16 12:08:46 ┆ -999.0        ┆ 0.68376       ┆ 0.122094                 │
│ 2002-04-17 10:31:29 ┆ -999.0        ┆ 0.707747      ┆ 0.147369                 │
└─────────────────────┴───────────────┴───────────────┴──────────────────────────┘

In [40]:
df = pl.read_csv('Sao_Paulo_AOD20.csv')
df.select(['time','AOD_500nm','Precipitable_Water(cm)']).head(5)

shape: (5, 3)
┌─────────────────────┬───────────┬────────────────────────┐
│ time                ┆ AOD_500nm ┆ Precipitable_Water(cm) │
│ ---                 ┆ ---       ┆ ---                    │
│ str                 ┆ f64       ┆ f64                    │
╞═════════════════════╪═══════════╪════════════════════════╡
│ 2010-10-12 12:00:00 ┆ 0.099469  ┆ 0.830675               │
│ 2010-10-13 12:00:00 ┆ 0.195643  ┆ 1.395453               │
│ 2010-10-14 12:00:00 ┆ 0.676282  ┆ 3.012284               │
│ 2010-10-16 12:00:00 ┆ 0.481589  ┆ 2.913485               │
│ 2010-10-17 12:00:00 ┆ 0.756076  ┆ 3.218981               │
└─────────────────────┴───────────┴────────────────────────┘

Interpolando a profundidade óptica em *550 nm*

In [41]:
pyAERONET.compute_AOD_550_polars(df).select(['time','AOD_440nm','AOD_550nm','AOD_675nm']).head(5)

shape: (5, 4)
┌─────────────────────┬───────────┬───────────┬───────────┐
│ time                ┆ AOD_440nm ┆ AOD_550nm ┆ AOD_675nm │
│ ---                 ┆ ---       ┆ ---       ┆ ---       │
│ str                 ┆ f64       ┆ f64       ┆ f64       │
╞═════════════════════╪═══════════╪═══════════╪═══════════╡
│ 2010-10-12 12:00:00 ┆ 0.121822  ┆ 0.087688  ┆ 0.071906  │
│ 2010-10-13 12:00:00 ┆ 0.239659  ┆ 0.169831  ┆ 0.128913  │
│ 2010-10-14 12:00:00 ┆ 0.828402  ┆ 0.579552  ┆ 0.412271  │
│ 2010-10-16 12:00:00 ┆ 0.571732  ┆ 0.421634  ┆ 0.31229   │
│ 2010-10-17 12:00:00 ┆ 0.875544  ┆ 0.673564  ┆ 0.516165  │
└─────────────────────┴───────────┴───────────┴───────────┘