In [20]:
import pyAERO
import polars as pl

Realizando o download do fator de assimetria e albedo de espalhamento simples

In [8]:
pyAERO.GetDataAEROET(station='Sao_Paulo',
                     start_date='2002-02-1',
                     end_date='2020-10-1',
                     vars='ALL',
                     inversion_type='ALM20',
                     temporal_type='all')

Finish Download: 100%|██████████| 3/3 [00:13<00:00,  4.41s/it]

# Reading the file

Veja que as propriedades são em linhas espectrais *440 nm*, *675 nm*, *870 nm* e *1020 nm*.

In [34]:
df = pl.read_csv('Sao_Paulo_ALL.csv',skip_rows=8)[:-1]
df = df.with_columns((pl.col('Date(dd:mm:yyyy)')+' '+pl.col('Time(hh:mm:ss)')).str.to_datetime(format='%d:%m:%Y %H:%M:%S').alias('time'))
df

shape: (2_490, 156)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ AERONET_S ┆ Date(dd:m ┆ Time(hh:m ┆ Day_of_Ye ┆ … ┆ Elevation ┆ Inversion ┆ Retrieval ┆ time     │
│ ite       ┆ m:yyyy)   ┆ m:ss)     ┆ ar        ┆   ┆ (m)       ┆ _Data_Qua ┆ _Measurem ┆ ---      │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ lity_Leve ┆ ent_Scan_ ┆ datetime │
│ str       ┆ str       ┆ str       ┆ i64       ┆   ┆ f64       ┆ l         ┆ Typ…      ┆ [μs]     │
│           ┆           ┆           ┆           ┆   ┆           ┆ ---       ┆ ---       ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆ str       ┆ str       ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ Sao_Paulo ┆ 11:04:200 ┆ 10:28:17  ┆ 101       ┆ … ┆ 786.0     ┆ lev20     ┆ Almucanta ┆ 2002-04- │
│           ┆ 2         ┆           ┆           ┆   ┆           ┆           ┆ r<br>     ┆ 11       │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 10:28:17 │
│ Sao_Paulo ┆ 11:04:200 ┆ 12:09:54  ┆ 101       ┆ … ┆ 786.0     ┆ lev20     ┆ Almucanta ┆ 2002-04- │
│           ┆ 2         ┆           ┆           ┆   ┆           ┆           ┆ r<br>     ┆ 11       │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 12:09:54 │
│ Sao_Paulo ┆ 16:04:200 ┆ 11:44:23  ┆ 106       ┆ … ┆ 786.0     ┆ lev20     ┆ Almucanta ┆ 2002-04- │
│           ┆ 2         ┆           ┆           ┆   ┆           ┆           ┆ r<br>     ┆ 16       │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 11:44:23 │
│ Sao_Paulo ┆ 16:04:200 ┆ 12:08:46  ┆ 106       ┆ … ┆ 786.0     ┆ lev20     ┆ Almucanta ┆ 2002-04- │
│           ┆ 2         ┆           ┆           ┆   ┆           ┆           ┆ r<br>     ┆ 16       │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 12:08:46 │
│ Sao_Paulo ┆ 17:04:200 ┆ 10:31:29  ┆ 107       ┆ … ┆ 786.0     ┆ lev20     ┆ Almucanta ┆ 2002-04- │
│           ┆ 2         ┆           ┆           ┆   ┆           ┆           ┆ r<br>     ┆ 17       │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 10:31:29 │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ Sao_Paulo ┆ 14:09:202 ┆ 10:14:11  ┆ 258       ┆ … ┆ 786.0     ┆ lev20     ┆ Almucanta ┆ 2020-09- │
│           ┆ 0         ┆           ┆           ┆   ┆           ┆           ┆ r<br>     ┆ 14       │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 10:14:11 │
│ Sao_Paulo ┆ 14:09:202 ┆ 10:36:27  ┆ 258       ┆ … ┆ 786.0     ┆ lev20     ┆ Almucanta ┆ 2020-09- │
│           ┆ 0         ┆           ┆           ┆   ┆           ┆           ┆ r<br>     ┆ 14       │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 10:36:27 │
│ Sao_Paulo ┆ 30:09:202 ┆ 11:05:22  ┆ 274       ┆ … ┆ 786.0     ┆ lev20     ┆ Almucanta ┆ 2020-09- │
│           ┆ 0         ┆           ┆           ┆   ┆           ┆           ┆ r<br>     ┆ 30       │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 11:05:22 │
│ Sao_Paulo ┆ 30:09:202 ┆ 11:32:20  ┆ 274       ┆ … ┆ 786.0     ┆ lev20     ┆ Almucanta ┆ 2020-09- │
│           ┆ 0         ┆           ┆           ┆   ┆           ┆           ┆ r<br>     ┆ 30       │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 11:32:20 │
│ Sao_Paulo ┆ 01:10:202 ┆ 09:56:11  ┆ 275       ┆ … ┆ 786.0     ┆ lev20     ┆ Almucanta ┆ 2020-10- │
│           ┆ 0         ┆           ┆           ┆   ┆           ┆           ┆ r<br>     ┆ 01       │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 09:56:11 │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [38]:
pyAERO.calcular_broadband_aeronet(df)['time','ssa_broadband'	,'asy_broadband',	'surface_albedo_broadband']

shape: (2_490, 4)
┌─────────────────────┬───────────────┬───────────────┬──────────────────────────┐
│ time                ┆ ssa_broadband ┆ asy_broadband ┆ surface_albedo_broadband │
│ ---                 ┆ ---           ┆ ---           ┆ ---                      │
│ datetime[μs]        ┆ f64           ┆ f64           ┆ f64                      │
╞═════════════════════╪═══════════════╪═══════════════╪══════════════════════════╡
│ 2002-04-11 10:28:17 ┆ -999.0        ┆ 0.741715      ┆ 0.150063                 │
│ 2002-04-11 12:09:54 ┆ -999.0        ┆ 0.686575      ┆ 0.12324                  │
│ 2002-04-16 11:44:23 ┆ -999.0        ┆ 0.686456      ┆ 0.125923                 │
│ 2002-04-16 12:08:46 ┆ -999.0        ┆ 0.68376       ┆ 0.122094                 │
│ 2002-04-17 10:31:29 ┆ -999.0        ┆ 0.707747      ┆ 0.147369                 │
│ …                   ┆ …             ┆ …             ┆ …                        │
│ 2020-09-14 10:14:11 ┆ 0.903814      ┆ 0.607741      ┆ 0.145617                 │
│ 2020-09-14 10:36:27 ┆ 0.890202      ┆ 0.614397      ┆ 0.136847                 │
│ 2020-09-30 11:05:22 ┆ 0.899603      ┆ 0.653706      ┆ 0.129738                 │
│ 2020-09-30 11:32:20 ┆ 0.906737      ┆ 0.640508      ┆ 0.124656                 │
│ 2020-10-01 09:56:11 ┆ 0.90331       ┆ 0.658891      ┆ 0.152735                 │
└─────────────────────┴───────────────┴───────────────┴──────────────────────────┘