# Some Examples

In [4]:
import pyAERONET

Download AOD

In [5]:
pyAERONET.download(station='Sao_Paulo',
         start_date='2010-01-01',
         end_date='2010-12-01',
         vars='AOD20',
         data_frequency='all')

Finish Download: 100%|██████████| 3/3 [00:11<00:00,  3.78s/it]

Interpolate aod to 550nm

In [1]:
import pandas as pd

In [8]:
df = pd.read_csv('Sao_Paulo_AOD20.csv')
pyAERONET.compute_AOD550nm(df,return_columns=['time','AOD_550nm','440-870_Angstrom_Exponent']).head(10)

                  time  AOD_550nm  440-870_Angstrom_Exponent
0  2010-01-04 10:48:58   0.202177                   1.376145
1  2010-01-04 11:27:34   0.183635                   1.034662
2  2010-01-04 14:57:39   0.201782                   1.464260
3  2010-01-04 15:27:38   0.163659                   1.514056
4  2010-01-05 11:43:01   0.291278                   1.058401
5  2010-01-05 12:43:02   0.293813                   1.012222
6  2010-01-05 18:13:02   0.169074                   1.326189
7  2010-01-05 18:28:02   0.135284                   1.281286
8  2010-01-09 09:53:31   0.154934                   1.092616
9  2010-01-09 10:04:20   0.156799                   1.064502

Visualizando os mesmos arquivos sem precisar baixar

Aqui estamos deixando os arquivos na memória do computador,
poderíamos utilizar um to_csv ou to_parquet para salvar. <br>

Caso você precise realizar download de múltiplas estações da AERONET, recomendo utilizar a
função download, lembre-se de utilizar o e-mail.

In [10]:
pyAERONET.view_data(station='Sao_Paulo',
         start_date='2010-01-01',
         end_date='2014-01-01',
         vars='AOD20',
         data_frequency='all').head(10)

,AERONET_Site,Date(dd:mm:yyyy),Time(hh:mm:ss),Day_of_Year,Day_of_Year(Fraction),AOD_1640nm,AOD_1020nm,AOD_870nm,AOD_865nm,AOD_779nm,...,Exact_Wavelengths_of_AOD(um)_340nm,Exact_Wavelengths_of_PW(um)_935nm,Exact_Wavelengths_of_AOD(um)_681nm,Exact_Wavelengths_of_AOD(um)_709nm,Exact_Wavelengths_of_AOD(um)_Empty,Exact_Wavelengths_of_AOD(um)_Empty_duplicated_0,Exact_Wavelengths_of_AOD(um)_Empty_duplicated_1,Exact_Wavelengths_of_AOD(um)_Empty_duplicated_2,Exact_Wavelengths_of_AOD(um)_Empty_duplicated_3,Principal_Investigator
0,Sao_Paulo,04:01:2010,10:48:58,4,4.450671,-999.0,-999.0,0.108997,-999.0,-999.0,...,0.3397,0.9362,-999.0,-999.0,-999.0,-999.0,-999.0,-999.0,-999.0,PI=Paulo_Artaxo; PI Email=artaxo@if.usp.br
1,Sao_Paulo,04:01:2010,11:27:34,4,4.477477,-999.0,-999.0,0.118856,-999.0,-999.0,...,0.3397,0.9362,-999.0,-999.0,-999.0,-999.0,-999.0,-999.0,-999.0,PI=Paulo_Artaxo; PI Email=artaxo@if.usp.br
2,Sao_Paulo,04:01:2010,14:57:39,4,4.623368,-999.0,-999.0,0.100304,-999.0,-999.0,...,0.3397,0.9362,-999.0,-999.0,-999.0,-999.0,-999.0,-999.0,-999.0,PI=Paulo_Artaxo; PI Email=artaxo@if.usp.br
3,Sao_Paulo,04:01:2010,15:27:38,4,4.644190,-999.0,-999.0,0.078488,-999.0,-999.0,...,0.3397,0.9362,-999.0,-999.0,-999.0,-999.0,-999.0,-999.0,-999.0,PI=Paulo_Artaxo; PI Email=artaxo@if.usp.br
4,Sao_Paulo,05:01:2010,11:43:01,5,5.488206,-999.0,-999.0,0.174075,-999.0,-999.0,...,0.3397,0.9362,-999.0,-999.0,-999.0,-999.0,-999.0,-999.0,-999.0,PI=Paulo_Artaxo; PI Email=artaxo@if.usp.br
5,Sao_Paulo,05:01:2010,12:43:02,5,5.529884,-999.0,-999.0,0.183394,-999.0,-999.0,...,0.3397,0.9362,-999.0,-999.0,-999.0,-999.0,-999.0,-999.0,-999.0,PI=Paulo_Artaxo; PI Email=artaxo@if.usp.br
6,Sao_Paulo,05:01:2010,18:13:02,5,5.759051,-999.0,-999.0,0.090616,-999.0,-999.0,...,0.3397,0.9362,-999.0,-999.0,-999.0,-999.0,-999.0,-999.0,-999.0,PI=Paulo_Artaxo; PI Email=artaxo@if.usp.br
7,Sao_Paulo,05:01:2010,18:28:02,5,5.769468,-999.0,-999.0,0.074362,-999.0,-999.0,...,0.3397,0.9362,-999.0,-999.0,-999.0,-999.0,-999.0,-999.0,-999.0,PI=Paulo_Artaxo; PI Email=artaxo@if.usp.br
8,Sao_Paulo,09:01:2010,09:53:31,9,9.412164,-999.0,-999.0,0.094001,-999.0,-999.0,...,0.3397,0.9362,-999.0,-999.0,-999.0,-999.0,-999.0,-999.0,-999.0,PI=Paulo_Artaxo; PI Email=artaxo@if.usp.br
9,Sao_Paulo,09:01:2010,10:04:20,9,9.419676,-999.0,-999.0,0.096086,-999.0,-999.0,...,0.3397,0.9362,-999.0,-999.0,-999.0,-999.0,-999.0,-999.0,-999.0,PI=Paulo_Artaxo; PI Email=artaxo@if.usp.br

Compute broadband of single scattering albedo, asymmetry factor and surface albedo.

In [11]:
# download the file of inversion
pyAERONET.download(station='Sao_Paulo',
         start_date='2010-01-01',
         end_date='2010-12-01',
         vars='ALL',
         inversion_type='ALM20',
         data_frequency='all')

Finish Download: 100%|██████████| 3/3 [00:09<00:00,  3.31s/it]

In [12]:
# open file and compute broadband
df_all = pd.read_csv('Sao_Paulo_ALL.csv')
pyAERONET.compute_broadband(df_all)[['time','ssa_broadband','asy_broadband','surface_albedo_broadband']].head(10)

                  time  ssa_broadband  asy_broadband  surface_albedo_broadband
0  2010-08-27 18:11:00       0.798428       0.608350                  0.114943
1  2010-08-27 18:33:28       0.801800       0.617090                  0.118449
2  2010-08-28 10:33:51       0.912606       0.712697                  0.135676
3  2010-08-28 10:56:51       0.905311       0.709768                  0.127809
4  2010-08-28 11:47:16       0.898936       0.701038                  0.116812
5  2010-08-28 12:10:46       0.873858       0.681571                  0.113560
6  2010-08-28 18:10:49       0.845685       0.624713                  0.114827
7  2010-08-28 18:34:16       0.835404       0.614897                  0.118487
8  2010-08-28 19:24:41       0.854191       0.620815                  0.130956
9  2010-08-28 19:48:57       0.848070       0.602718                  0.140593