In [5]:
import pyAERONET
import polars as pl

In [12]:
df = pl.read_csv('Sao_Paulo_AOD20.csv')
df.select(['time','AOD_500nm','Precipitable_Water(cm)']).head(5)

shape: (5, 3)
┌─────────────────────┬───────────┬────────────────────────┐
│ time                ┆ AOD_500nm ┆ Precipitable_Water(cm) │
│ ---                 ┆ ---       ┆ ---                    │
│ str                 ┆ f64       ┆ f64                    │
╞═════════════════════╪═══════════╪════════════════════════╡
│ 2010-10-12 12:00:00 ┆ 0.099469  ┆ 0.830675               │
│ 2010-10-13 12:00:00 ┆ 0.195643  ┆ 1.395453               │
│ 2010-10-14 12:00:00 ┆ 0.676282  ┆ 3.012284               │
│ 2010-10-16 12:00:00 ┆ 0.481589  ┆ 2.913485               │
│ 2010-10-17 12:00:00 ┆ 0.756076  ┆ 3.218981               │
└─────────────────────┴───────────┴────────────────────────┘

In [16]:
pyAERONET.compute_AOD_550_polars(df).select(['time','AOD_440nm','AOD_550nm','AOD_675nm']).head(5)

shape: (5, 4)
┌─────────────────────┬───────────┬───────────┬───────────┐
│ time                ┆ AOD_440nm ┆ AOD_550nm ┆ AOD_675nm │
│ ---                 ┆ ---       ┆ ---       ┆ ---       │
│ str                 ┆ f64       ┆ f64       ┆ f64       │
╞═════════════════════╪═══════════╪═══════════╪═══════════╡
│ 2010-10-12 12:00:00 ┆ 0.121822  ┆ 0.087688  ┆ 0.071906  │
│ 2010-10-13 12:00:00 ┆ 0.239659  ┆ 0.169831  ┆ 0.128913  │
│ 2010-10-14 12:00:00 ┆ 0.828402  ┆ 0.579552  ┆ 0.412271  │
│ 2010-10-16 12:00:00 ┆ 0.571732  ┆ 0.421634  ┆ 0.31229   │
│ 2010-10-17 12:00:00 ┆ 0.875544  ┆ 0.673564  ┆ 0.516165  │
└─────────────────────┴───────────┴───────────┴───────────┘